# Generated by Django 4.1.2 on 2022-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
